language: node_js
git:
  submodules: false
jobs:
  include:
    - stage: "Test"
      name: "Unit Tests: node latest"
      node_js: "node"
      script: npm test
    - name: "Unit Tests: node 10"
      node_js: "10"
      script: npm test
    - name: "Linter"
      node_js: "node"
      script: npm run eslint
    - stage: "Coveralls Report"
      node_js: "node"
      script: npm run coveralls
