language: node_js
node_js:
  - "node"
  - "10"
git:
  submodules: false
jobs:
  include:
    - stage: "test"
      script: npm run eslint
    - script: npm t
    - stage: "coveralls report"
      node_js: "10"
      script: npm run coveralls
