language: node_js
node_js:
  - "node"
  - "10"
git:
  submodules: false
jobs:
  include:
    - stage: "test"
      script: npm test
    - script: npm run eslint
    - stage: "coveralls report"
      node_js: "node"
      script: npm run coveralls
